import org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

plugins {
    kotlin("jvm") version "2.1.21" apply false
    id("com.google.devtools.ksp") version "2.1.21-2.0.2" apply false
    id("com.vanniktech.maven.publish") version "0.34.0" apply false
}

subprojects {
    pluginManager.withPlugin("org.jetbrains.kotlin.jvm") {
        extensions.configure<KotlinJvmProjectExtension> {
            compilerOptions {
                languageVersion.set(KotlinVersion.KOTLIN_2_1)
                apiVersion.set(KotlinVersion.KOTLIN_2_1)
            }
        }
    }
    pluginManager.withPlugin("com.vanniktech.maven.publish") {
        extensions.configure<com.vanniktech.maven.publish.MavenPublishBaseExtension> {
            coordinates(
                groupId = rootProject.property("differGroup") as String,
                artifactId = project.name,
                version = rootProject.property("differVersion") as String,
            )
            publishToMavenCentral()
            if (System.getenv("CI") == "true") {
                signAllPublications()
            }
            pom {
                name.set(project.name)
                description.set("Typed, ID-keyed diffs for Kotlin data classes, generated by KSP.")
                inceptionYear.set("2026")
                url.set("https://github.com/ultish/differ")
                licenses {
                    license {
                        name.set("MIT License")
                        url.set("https://opensource.org/licenses/MIT")
                        distribution.set("repo")
                    }
                }
                developers {
                    developer {
                        id.set("ultish")
                        name.set("ultish")
                        url.set("https://github.com/ultish")
                    }
                }
                scm {
                    url.set("https://github.com/ultish/differ")
                    connection.set("scm:git:git://github.com/ultish/differ.git")
                    developerConnection.set("scm:git:ssh://git@github.com/ultish/differ.git")
                }
            }
        }
    }
}
