package hana.differ.it

import hana.differ.Differ
import hana.differ.Tracked

@Differ
data class Fat(
    @Tracked val f00: Int,
    @Tracked val f01: Int,
    @Tracked val f02: Int,
    @Tracked val f03: Int,
    @Tracked val f04: Int,
    @Tracked val f05: Int,
    @Tracked val f06: Int,
    @Tracked val f07: Int,
    @Tracked val f08: Int,
    @Tracked val f09: Int,
    @Tracked val f10: Int,
    @Tracked val f11: Int,
    @Tracked val f12: Int,
    @Tracked val f13: Int,
    @Tracked val f14: Int,
    @Tracked val f15: Int,
    @Tracked val f16: Int,
    @Tracked val f17: Int,
    @Tracked val f18: Int,
    @Tracked val f19: Int,
    @Tracked val f20: Int,
    @Tracked val f21: Int,
    @Tracked val f22: Int,
    @Tracked val f23: Int,
    @Tracked val f24: Int,
    @Tracked val f25: Int,
    @Tracked val f26: Int,
    @Tracked val f27: Int,
    @Tracked val f28: Int,
    @Tracked val f29: Int,
    @Tracked val f30: Int,
    @Tracked val f31: Int,
    @Tracked val f32: Int,
    @Tracked val f33: Int,
    @Tracked val f34: Int,
    @Tracked val f35: Int,
    @Tracked val f36: Int,
    @Tracked val f37: Int,
    @Tracked val f38: Int,
    @Tracked val f39: Int,
    @Tracked val f40: Int,
    @Tracked val f41: Int,
    @Tracked val f42: Int,
    @Tracked val f43: Int,
    @Tracked val f44: Int,
    @Tracked val f45: Int,
    @Tracked val f46: Int,
    @Tracked val f47: Int,
    @Tracked val f48: Int,
    @Tracked val f49: Int,
    @Tracked val f50: Int,
    @Tracked val f51: Int,
    @Tracked val f52: Int,
    @Tracked val f53: Int,
    @Tracked val f54: Int,
    @Tracked val f55: Int,
    @Tracked val f56: Int,
    @Tracked val f57: Int,
    @Tracked val f58: Int,
    @Tracked val f59: Int,
    @Tracked val f60: Int,
    @Tracked val f61: Int,
    @Tracked val f62: Int,
    @Tracked val f63: Int,
    @Tracked val f64: Int,
    @Tracked val f65: Int,
    @Tracked val f66: Int,
    @Tracked val f67: Int,
    @Tracked val f68: Int,
    @Tracked val f69: Int,
)
