package hana.differ.processor

import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.getDeclaredProperties
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LONG
import com.squareup.kotlinpoet.MAP
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asClassName
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo
import hana.differ.processor.Node.KeyedList
import hana.differ.processor.Node.KeyedMap
import hana.differ.processor.Node.Nested
import hana.differ.processor.Node.Scalar

class DifferProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        DifferProcessor(environment.codeGenerator, environment.logger)
}

private const val ANNOTATION_PACKAGE = "hana.differ"
private const val DIFFER = "$ANNOTATION_PACKAGE.Differ"
private const val TRACKED = "$ANNOTATION_PACKAGE.Tracked"
private const val TRACKED_NESTED = "$ANNOTATION_PACKAGE.TrackedNested"
private const val TRACKED_LIST = "$ANNOTATION_PACKAGE.TrackedList"
private const val TRACKED_MAP = "$ANNOTATION_PACKAGE.TrackedMap"

private val DIFFER_SUPPORT = ClassName(ANNOTATION_PACKAGE, "DifferSupport")
private val VALUE_CHANGE = ClassName(ANNOTATION_PACKAGE, "ValueChange")
private val DUPLICATE_CHILD_ID = ClassName(ANNOTATION_PACKAGE, "DuplicateChildIdException")

class DifferProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    private val generated = HashSet<String>()
    private lateinit var resolver: Resolver

    override fun process(resolver: Resolver): List<KSAnnotated> {
        this.resolver = resolver
        resolver.getSymbolsWithAnnotation(DIFFER)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { generate(it) }
        return emptyList()
    }

    private fun generate(cls: KSClassDeclaration) {
        val id = cls.qualifiedName?.asString() ?: return
        if (!generated.add(id)) return
        val annotation = cls.annotationOf(DIFFER) ?: return
        val model = cls.toClassName()
        val objectName = (annotation.argument("name") as? String)
            ?.takeIf { it.isNotBlank() }
            ?: "${cls.simpleName.asString()}Differ"
        val diffName = "${cls.simpleName.asString()}Diff"
        val changeName = "${cls.simpleName.asString()}Change"

        val captureAll = (annotation.argument("captureValues") as? Boolean) ?: true
        val counter = intArrayOf(0)
        val roots = analyze(
            cls,
            path = "",
            bag = null,
            counter = counter,
            ownerName = cls.simpleName.asString(),
            forceNoCapture = !captureAll,
        )
        val slotCount = counter[0]
        if (slotCount == 0) {
            logger.warn("@Differ class has no @Tracked properties; skipping", cls)
            return
        }
        val bags = roots.flatMap { it.bags() }
        val slots = roots.flatMap { it.slots() }
        val pkg = model.packageName
        val changeType = ClassName(pkg, changeName)
        val diffType = ClassName(pkg, diffName)

        val file = FileSpec.builder(pkg, objectName)
            .addFileComment("Generated by Differ. Do not edit.")
            .addType(changeInterface(changeType, roots))
            .apply { bags.forEach { addType(deltaClass(it)) } }
            .addType(rebuildDiffClass(diffType, slots, bags, changeType, compactMask = slotCount <= 64))
            .addType(differObject(objectName, model, diffType, changeType, roots, bags, slotCount))
            .build()
        file.writeTo(codeGenerator, aggregating = false, originatingKSFiles = listOfNotNull(cls.containingFile))
    }

    private fun analyze(
        cls: KSClassDeclaration,
        path: String,
        bag: KeyedBag?,
        counter: IntArray,
        ownerName: String,
        forceNoCapture: Boolean,
    ): List<Node> {
        val out = ArrayList<Node>()
        for (prop in cls.getDeclaredProperties()) {
            val name = prop.simpleName.asString()
            when {
                prop.annotationOf(TRACKED) != null -> {
                    val capture = if (forceNoCapture) {
                        false
                    } else {
                        (prop.annotationOf(TRACKED)!!.argument("captureValues") as? Boolean) ?: true
                    }
                    val index = counter[0]++
                    val slotPath = path + name
                    out += Scalar(
                        index = index,
                        name = name,
                        path = slotPath,
                        type = prop.type.toTypeName(),
                        captureValues = capture,
                        hasName = hasName(slotPath),
                        changeName = typeName(slotPath),
                        bag = bag,
                        deltaProp = bag?.let { deltaField(slotPath, it.name) },
                    )
                }
                prop.annotationOf(TRACKED_NESTED) != null -> {
                    val child = prop.classDeclaration() ?: run {
                        logger.error("@TrackedNested property is not a class type", prop)
                        return out
                    }
                    val slotPath = path + name
                    val nullable = prop.type.resolve().isMarkedNullable
                    val presenceIndex = if (nullable) counter[0]++ else null
                    out += Nested(
                        name = name,
                        children = analyze(child, "$path$name.", bag, counter, ownerName, forceNoCapture),
                        type = prop.type.toTypeName(),
                        nullable = nullable,
                        presenceIndex = presenceIndex,
                        hasName = if (nullable) hasName(slotPath) else null,
                        changeName = if (nullable) typeName(slotPath) else null,
                        bag = bag,
                        deltaProp = if (nullable) bag?.let { deltaField(slotPath, it.name) } else null,
                    )
                }
                prop.annotationOf(TRACKED_LIST) != null -> {
                    val matchBy = (prop.annotationOf(TRACKED_LIST)!!.argument("matchBy") as? String) ?: "id"
                    val collection = prop.type.resolve()
                    val kind = collection.sequenceKind()
                    if (kind == null || kind == CollectionKind.MAP) {
                        logger.error("@TrackedList property must be a List or Set of a class type", prop)
                        return out
                    }
                    val element = prop.elementDeclaration() ?: run {
                        logger.error("@TrackedList property must be a List or Set of a class type", prop)
                        return out
                    }
                    val keyProp = element.getDeclaredProperties().firstOrNull { it.simpleName.asString() == matchBy }
                    if (keyProp == null) {
                        logger.error("@TrackedList matchBy '$matchBy' not found on ${element.simpleName.asString()}", prop)
                        return out
                    }
                    val added = counter[0]++
                    val removed = counter[0]++
                    val addedPath = "$path$name[+]"
                    val removedPath = "$path$name[-]"
                    val spec = KeyedList(
                        name = name,
                        matchBy = matchBy,
                        keyType = keyProp.type.toTypeName(),
                        elementType = element.toClassName(),
                        addedIndex = added,
                        removedIndex = removed,
                        addedHas = hasName(addedPath),
                        removedHas = hasName(removedPath),
                        addedChange = typeName(addedPath),
                        removedChange = typeName(removedPath),
                        deltaName = ownerName + typeName(name) + "Change",
                        nullable = collection.isMarkedNullable,
                        kind = kind,
                        children = emptyList(),
                    )
                    val children = analyze(element, "$path$name[].", spec, counter, ownerName, forceNoCapture)
                    out += spec.copy(children = children)
                }
                prop.annotationOf(TRACKED_MAP) != null -> {
                    val collection = prop.type.resolve()
                    if (collection.sequenceKind() != CollectionKind.MAP) {
                        logger.error("@TrackedMap property must be a Map", prop)
                        return out
                    }
                    val args = collection.makeNotNullable().arguments
                    val keyKs = args.getOrNull(0)?.type?.resolve()
                    val valueKs = args.getOrNull(1)?.type?.resolve()
                    if (keyKs == null || valueKs == null) {
                        logger.error("@TrackedMap property must be a Map<K, V>", prop)
                        return out
                    }
                    val added = counter[0]++
                    val removed = counter[0]++
                    val addedPath = "$path$name[+]"
                    val removedPath = "$path$name[-]"
                    val spec = KeyedMap(
                        name = name,
                        keyType = keyKs.toTypeName(),
                        valueType = valueKs.toTypeName(),
                        addedIndex = added,
                        removedIndex = removed,
                        addedHas = hasName(addedPath),
                        removedHas = hasName(removedPath),
                        addedChange = typeName(addedPath),
                        removedChange = typeName(removedPath),
                        deltaName = ownerName + typeName(name) + "Change",
                        nullable = collection.isMarkedNullable,
                        children = emptyList(),
                    )
                    val children = if (valueKs.isScalarValue()) {
                        val slotPath = "$path$name[]"
                        listOf(
                            Scalar(
                                index = counter[0]++,
                                name = "",
                                path = slotPath,
                                type = valueKs.toTypeName(),
                                captureValues = !forceNoCapture,
                                hasName = hasName(slotPath),
                                changeName = typeName(slotPath),
                                bag = spec,
                                deltaProp = "value",
                            ),
                        )
                    } else {
                        val valueClass = valueKs.declaration as? KSClassDeclaration ?: run {
                            logger.error("@TrackedMap value type is not a class", prop)
                            return out
                        }
                        analyze(valueClass, "$path$name[].", spec, counter, ownerName, forceNoCapture)
                    }
                    out += spec.copy(children = children)
                }
            }
        }
        return out
    }

    private fun changeInterface(changeType: ClassName, roots: List<Node>): TypeSpec {
        val spec = TypeSpec.interfaceBuilder(changeType)
            .addModifiers(KModifier.SEALED)
        for (node in roots.asSequence().flatMap { it.walk() }) {
            when (node) {
                is Scalar -> spec.addType(scalarChange(changeType, node))
                is KeyedList -> {
                    spec.addType(boundChange(changeType, node.addedChange, node.keyType, node.elementType))
                    spec.addType(boundChange(changeType, node.removedChange, node.keyType, node.elementType))
                }
                is KeyedMap -> {
                    spec.addType(boundChange(changeType, node.addedChange, node.keyType, node.valueType))
                    spec.addType(boundChange(changeType, node.removedChange, node.keyType, node.valueType))
                }
                is Nested -> if (node.presenceIndex != null) spec.addType(presenceChange(changeType, node))
            }
        }
        return spec.build()
    }

    private fun scalarChange(changeType: ClassName, node: Scalar): TypeSpec {
        if (!node.captureValues) {
            return TypeSpec.objectBuilder(node.changeName)
                .addModifiers(KModifier.DATA)
                .addSuperinterface(changeType)
                .build()
        }
        val ctor = FunSpec.constructorBuilder()
        val type = TypeSpec.classBuilder(node.changeName)
            .addModifiers(KModifier.DATA)
            .addSuperinterface(changeType)
        if (node.bag != null) {
            ctor.addParameter("id", node.bag.keyType)
            type.addProperty(PropertySpec.builder("id", node.bag.keyType).initializer("id").build())
        }
        ctor.addParameter("old", node.type)
        ctor.addParameter("new", node.type)
        type.addProperty(PropertySpec.builder("old", node.type).initializer("old").build())
        type.addProperty(PropertySpec.builder("new", node.type).initializer("new").build())
        type.primaryConstructor(ctor.build())
        return type.build()
    }

    private fun presenceChange(changeType: ClassName, node: Nested): TypeSpec {
        val ctor = FunSpec.constructorBuilder()
        val type = TypeSpec.classBuilder(node.changeName!!)
            .addModifiers(KModifier.DATA)
            .addSuperinterface(changeType)
        if (node.bag != null) {
            ctor.addParameter("id", node.bag.keyType)
            type.addProperty(PropertySpec.builder("id", node.bag.keyType).initializer("id").build())
        }
        ctor.addParameter("old", node.type)
        ctor.addParameter("new", node.type)
        type.addProperty(PropertySpec.builder("old", node.type).initializer("old").build())
        type.addProperty(PropertySpec.builder("new", node.type).initializer("new").build())
        type.primaryConstructor(ctor.build())
        return type.build()
    }

    private fun boundChange(changeType: ClassName, name: String, keyType: TypeName, elementType: TypeName): TypeSpec {
        return TypeSpec.classBuilder(name)
            .addModifiers(KModifier.DATA)
            .addSuperinterface(changeType)
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("id", keyType)
                    .addParameter("item", elementType)
                    .build(),
            )
            .addProperty(PropertySpec.builder("id", keyType).initializer("id").build())
            .addProperty(PropertySpec.builder("item", elementType).initializer("item").build())
            .build()
    }

    private fun deltaClass(bag: KeyedBag): TypeSpec {
        val spec = TypeSpec.classBuilder(bag.deltaName)
        for (field in bag.deltaFields()) {
            val t = VALUE_CHANGE.parameterizedBy(field.type).copy(nullable = true)
            spec.addProperty(
                PropertySpec.builder(field.prop, t)
                    .mutable()
                    .initializer("null")
                    .build(),
            )
        }
        return spec.build()
    }

    private fun rebuildDiffClass(
        diffType: ClassName,
        slots: List<HasBit>,
        bags: List<KeyedBag>,
        changeType: ClassName,
        compactMask: Boolean,
    ): TypeSpec {
        val maskType = if (compactMask) LONG else LongArray::class.asClassName()
        val ctor = FunSpec.constructorBuilder().addModifiers(KModifier.INTERNAL)
        ctor.addParameter("mask", maskType)
        ctor.addParameter("changes", List::class.asClassName().parameterizedBy(changeType))
        for (bag in bags) {
            ctor.addParameter(bag.name, MAP.parameterizedBy(bag.keyType, ClassName(diffType.packageName, bag.deltaName)))
        }
        val type = TypeSpec.classBuilder(diffType).primaryConstructor(ctor.build())
        type.addProperty(PropertySpec.builder("mask", maskType, KModifier.PRIVATE).initializer("mask").build())
        type.addProperty(
            PropertySpec.builder("changes", List::class.asClassName().parameterizedBy(changeType))
                .initializer("changes")
                .build(),
        )
        val changedGetter = FunSpec.getterBuilder()
        if (compactMask) changedGetter.addStatement("return mask != 0L")
        else changedGetter.addStatement("return %T.any(mask)", DIFFER_SUPPORT)
        type.addProperty(
            PropertySpec.builder("hasChanged", Boolean::class)
                .getter(changedGetter.build())
                .build(),
        )
        for (slot in slots) {
            val bitGetter = FunSpec.getterBuilder()
            if (compactMask) {
                bitGetter.addStatement("return mask and (1L shl %L) != 0L", slot.index)
            } else {
                bitGetter.addStatement("return %T.test(mask, %L)", DIFFER_SUPPORT, slot.index)
            }
            type.addProperty(
                PropertySpec.builder(slot.hasName, Boolean::class)
                    .getter(bitGetter.build())
                    .build(),
            )
        }
        for (bag in bags) {
            val mapType = MAP.parameterizedBy(bag.keyType, ClassName(diffType.packageName, bag.deltaName))
            type.addProperty(PropertySpec.builder(bag.name, mapType).initializer(bag.name).build())
        }
        return type.build()
    }

    private fun differObject(
        objectName: String,
        model: ClassName,
        diffType: ClassName,
        changeType: ClassName,
        roots: List<Node>,
        bags: List<KeyedBag>,
        slotCount: Int,
    ): TypeSpec {
        val compactMask = slotCount <= 64
        val emit = Emit(changeType, compactMask, ArrayList())
        val body = CodeBlock.builder()
        if (compactMask) {
            body.addStatement("var mask = 0L")
        } else {
            body.addStatement("val mask = %T.bits(%L)", DIFFER_SUPPORT, slotCount)
        }
        body.addStatement("var changes: %T = null", MUTABLE_CHANGE_LIST.parameterizedBy(changeType).copy(nullable = true))
        for (bag in bags) {
            val map = HASH_MAP.parameterizedBy(bag.keyType, ClassName(model.packageName, bag.deltaName))
            body.addStatement("var ${bag.name}: %T = null", map.copy(nullable = true))
        }
        emitNodes(body, roots, oldExpr = "old", newExpr = "new", depth = 0, keyLocal = null, emit = emit)
        val emptyArgs = StringBuilder("%T(${if (compactMask) "0L" else "%T.bits($slotCount)"}, emptyList()")
        val emptyFmt = ArrayList<Any>()
        emptyFmt += diffType
        if (!compactMask) emptyFmt += DIFFER_SUPPORT
        for (bag in bags) emptyArgs.append(", emptyMap()")
        emptyArgs.append(")")
        if (compactMask) {
            body.beginControlFlow("if (mask == 0L)")
        } else {
            body.beginControlFlow("if (!%T.any(mask))", DIFFER_SUPPORT)
        }
        body.addStatement("return EMPTY")
        body.endControlFlow()
        val built = StringBuilder("return %T(mask, changes ?: emptyList()")
        val builtFmt = ArrayList<Any>()
        builtFmt += diffType
        for (bag in bags) built.append(", ${bag.name} ?: emptyMap()")
        built.append(")")
        body.addStatement(built.toString(), *builtFmt.toTypedArray())

        val spec = TypeSpec.objectBuilder(objectName)
            .addProperty(
                PropertySpec.builder("EMPTY", diffType, KModifier.PRIVATE)
                    .initializer(emptyArgs.toString(), *emptyFmt.toTypedArray())
                    .build(),
            )
            .addFunction(
                FunSpec.builder("diff")
                    .addParameter("old", model)
                    .addParameter("new", model)
                    .returns(diffType)
                    .addCode(body.build())
                    .build(),
            )
        for (fn in emit.recorders) spec.addFunction(fn)
        return spec.build()
    }

    private class Emit(
        val changeType: ClassName,
        val compactMask: Boolean,
        val recorders: MutableList<FunSpec>,
    )

    private fun emitSetBit(out: CodeBlock.Builder, slot: Int, emit: Emit) {
        if (emit.compactMask) out.addStatement("mask = mask or (1L shl %L)", slot)
        else out.addStatement("%T.set(mask, %L)", DIFFER_SUPPORT, slot)
    }

    private fun emitNodes(
        out: CodeBlock.Builder,
        nodes: List<Node>,
        oldExpr: String,
        newExpr: String,
        depth: Int,
        keyLocal: String?,
        emit: Emit,
    ) {
        for (node in nodes) {
            when (node) {
                is Scalar -> emitScalar(out, node, oldExpr, newExpr, keyLocal, emit)
                is Nested -> emitNested(out, node, oldExpr, newExpr, depth, keyLocal, emit)
                is KeyedList -> emitList(out, node, oldExpr, newExpr, depth, emit)
                is KeyedMap -> emitMap(out, node, oldExpr, newExpr, depth, emit)
            }
        }
    }

    private fun emitNested(
        out: CodeBlock.Builder,
        node: Nested,
        oldExpr: String,
        newExpr: String,
        depth: Int,
        keyLocal: String?,
        emit: Emit,
    ) {
        val oldAccess = "$oldExpr.${node.name}"
        val newAccess = "$newExpr.${node.name}"
        if (!node.nullable) {
            emitNodes(out, node.children, oldAccess, newAccess, depth, keyLocal, emit)
            return
        }
        val presence = node.presenceIndex ?: return
        out.beginControlFlow("if ($oldAccess == null && $newAccess == null)")
        out.nextControlFlow("else if ($oldAccess == null || $newAccess == null)")
        emitSetBit(out, presence, emit)
        emitRecordPresence(out, node, oldAccess, newAccess, keyLocal, emit)
        out.nextControlFlow("else")
        emitNodes(out, node.children, oldAccess, newAccess, depth, keyLocal, emit)
        out.endControlFlow()
    }

    private fun emitScalar(
        out: CodeBlock.Builder,
        node: Scalar,
        oldExpr: String,
        newExpr: String,
        keyLocal: String?,
        emit: Emit,
    ) {
        val oldAccess = if (node.name.isEmpty()) oldExpr else "$oldExpr.${node.name}"
        val newAccess = if (node.name.isEmpty()) newExpr else "$newExpr.${node.name}"
        out.beginControlFlow("if ($oldAccess != $newAccess)")
        emitSetBit(out, node.index, emit)
        emitRecordScalar(out, node, oldAccess, newAccess, keyLocal, emit)
        out.endControlFlow()
    }

    private fun emitList(
        out: CodeBlock.Builder,
        list: KeyedList,
        oldExpr: String,
        newExpr: String,
        depth: Int,
        emit: Emit,
    ) {
        val d = depth
        val oldItems = "oldItems$d"
        val newItems = "newItems$d"
        val index = "index$d"
        val item = "item$d"
        val key = "k$d"
        val prior = "prior$d"
        val idArg = if (list.keyType.copy(nullable = false) == STRING) "stored" else "stored.toString()"

        out.beginControlFlow("run")
        out.addStatement("val $oldItems = %L", list.snapshot("$oldExpr.${list.name}"))
        out.addStatement("val $newItems = %L", list.snapshot("$newExpr.${list.name}"))
        out.addStatement("val $index = %T<%T, %T>($oldItems.size * 2)", HASH_MAP, list.keyType, list.elementType)
        out.beginControlFlow("for ($item in $oldItems)")
        out.addStatement("val stored = $item.${list.matchBy}")
        out.addStatement("if ($index.put(stored, $item) != null) throw %T(%L)", DUPLICATE_CHILD_ID, idArg)
        out.endControlFlow()
        out.beginControlFlow("for ($item in $newItems)")
        out.addStatement("val $key = $item.${list.matchBy}")
        out.addStatement("val $prior = $index.remove($key)")
        out.beginControlFlow("if ($prior == null)")
        emitSetBit(out, list.addedIndex, emit)
        emitRecordBound(out, list.addedChange, list.keyType, list.elementType, key, item, emit)
        out.addStatement("continue")
        out.endControlFlow()
        emitNodes(out, list.children, prior, item, depth, key, emit)
        out.endControlFlow()
        out.beginControlFlow("for ($item in $oldItems)")
        out.beginControlFlow("if ($index.containsKey($item.${list.matchBy}))")
        emitSetBit(out, list.removedIndex, emit)
        emitRecordBound(out, list.removedChange, list.keyType, list.elementType, "$item.${list.matchBy}", item, emit)
        out.endControlFlow()
        out.endControlFlow()
        out.endControlFlow()
    }

    private fun emitMap(
        out: CodeBlock.Builder,
        map: KeyedMap,
        oldExpr: String,
        newExpr: String,
        depth: Int,
        emit: Emit,
    ) {
        val d = depth
        val oldMap = "oldMap$d"
        val newMap = "newMap$d"
        val key = "k$d"
        val item = "item$d"
        val prior = "prior$d"

        out.beginControlFlow("run")
        out.addStatement("val $oldMap = %L", map.snapshot("$oldExpr.${map.name}"))
        out.addStatement("val $newMap = %L", map.snapshot("$newExpr.${map.name}"))
        out.beginControlFlow("for (($key, $item) in $newMap)")
        out.addStatement("val $prior = $oldMap[$key]")
        out.beginControlFlow("if ($prior == null)")
        emitSetBit(out, map.addedIndex, emit)
        emitRecordBound(out, map.addedChange, map.keyType, map.valueType, key, item, emit)
        out.addStatement("continue")
        out.endControlFlow()
        emitNodes(out, map.children, prior, item, depth, key, emit)
        out.endControlFlow()
        out.beginControlFlow("for (($key, $prior) in $oldMap)")
        out.beginControlFlow("if ($key !in $newMap)")
        emitSetBit(out, map.removedIndex, emit)
        emitRecordBound(out, map.removedChange, map.keyType, map.valueType, key, prior, emit)
        out.endControlFlow()
        out.endControlFlow()
        out.endControlFlow()
    }

    private fun emitRecordScalar(
        out: CodeBlock.Builder,
        node: Scalar,
        oldAccess: String,
        newAccess: String,
        keyLocal: String?,
        emit: Emit,
    ) {
        val rec = "rec${node.changeName}"
        val changeList = MUTABLE_CHANGE_LIST.parameterizedBy(emit.changeType).copy(nullable = true)
        if (!node.captureValues) {
            remember(emit, rec) {
                FunSpec.builder(rec)
                    .addModifiers(KModifier.PRIVATE)
                    .addParameter("changes", changeList)
                    .returns(changeList.copy(nullable = false))
                    .addStatement("return %T.add(changes, %T.%N)", DIFFER_SUPPORT, emit.changeType, node.changeName)
                    .build()
            }
            out.addStatement("changes = $rec(changes)")
            return
        }
        if (node.bag != null && keyLocal != null && node.deltaProp != null) {
            val deltaType = ClassName(emit.changeType.packageName, node.bag.deltaName)
            val bagType = HASH_MAP.parameterizedBy(node.bag.keyType, deltaType).copy(nullable = true)
            remember(emit, rec) {
                FunSpec.builder(rec)
                    .addModifiers(KModifier.PRIVATE)
                    .addParameter("changes", changeList)
                    .addParameter("bag", bagType)
                    .addParameter("id", node.bag.keyType)
                    .addParameter("old", node.type)
                    .addParameter("new", node.type)
                    .returns(PAIR.parameterizedBy(changeList.copy(nullable = false), bagType.copy(nullable = false)))
                    .addStatement(
                        "val next = %T.add(changes, %T.%N(id, old, new))",
                        DIFFER_SUPPORT, emit.changeType, node.changeName,
                    )
                    .addStatement("val held = %T.child(bag, id) { %T() }", DIFFER_SUPPORT, deltaType)
                    .addStatement("held.value.${node.deltaProp} = %T(old, new)", VALUE_CHANGE)
                    .addStatement("return %T(next, held.map)", PAIR)
                    .build()
            }
            out.addStatement("val recorded = $rec(changes, ${node.bag.name}, $keyLocal, $oldAccess, $newAccess)")
            out.addStatement("changes = recorded.first")
            out.addStatement("${node.bag.name} = recorded.second")
            return
        }
        remember(emit, rec) {
            FunSpec.builder(rec)
                .addModifiers(KModifier.PRIVATE)
                .addParameter("changes", changeList)
                .addParameter("old", node.type)
                .addParameter("new", node.type)
                .returns(changeList.copy(nullable = false))
                .addStatement(
                    "return %T.add(changes, %T.%N(old, new))",
                    DIFFER_SUPPORT, emit.changeType, node.changeName,
                )
                .build()
        }
        out.addStatement("changes = $rec(changes, $oldAccess, $newAccess)")
    }

    private fun emitRecordPresence(
        out: CodeBlock.Builder,
        node: Nested,
        oldAccess: String,
        newAccess: String,
        keyLocal: String?,
        emit: Emit,
    ) {
        val rec = "rec${node.changeName}"
        val changeList = MUTABLE_CHANGE_LIST.parameterizedBy(emit.changeType).copy(nullable = true)
        if (node.bag != null && keyLocal != null && node.deltaProp != null) {
            val deltaType = ClassName(emit.changeType.packageName, node.bag.deltaName)
            val bagType = HASH_MAP.parameterizedBy(node.bag.keyType, deltaType).copy(nullable = true)
            remember(emit, rec) {
                FunSpec.builder(rec)
                    .addModifiers(KModifier.PRIVATE)
                    .addParameter("changes", changeList)
                    .addParameter("bag", bagType)
                    .addParameter("id", node.bag.keyType)
                    .addParameter("old", node.type)
                    .addParameter("new", node.type)
                    .returns(PAIR.parameterizedBy(changeList.copy(nullable = false), bagType.copy(nullable = false)))
                    .addStatement(
                        "val next = %T.add(changes, %T.%N(id, old, new))",
                        DIFFER_SUPPORT, emit.changeType, node.changeName!!,
                    )
                    .addStatement("val held = %T.child(bag, id) { %T() }", DIFFER_SUPPORT, deltaType)
                    .addStatement("held.value.${node.deltaProp} = %T(old, new)", VALUE_CHANGE)
                    .addStatement("return %T(next, held.map)", PAIR)
                    .build()
            }
            out.addStatement("val recorded = $rec(changes, ${node.bag.name}, $keyLocal, $oldAccess, $newAccess)")
            out.addStatement("changes = recorded.first")
            out.addStatement("${node.bag.name} = recorded.second")
            return
        }
        remember(emit, rec) {
            FunSpec.builder(rec)
                .addModifiers(KModifier.PRIVATE)
                .addParameter("changes", changeList)
                .addParameter("old", node.type)
                .addParameter("new", node.type)
                .returns(changeList.copy(nullable = false))
                .addStatement(
                    "return %T.add(changes, %T.%N(old, new))",
                    DIFFER_SUPPORT, emit.changeType, node.changeName!!,
                )
                .build()
        }
        out.addStatement("changes = $rec(changes, $oldAccess, $newAccess)")
    }

    private fun emitRecordBound(
        out: CodeBlock.Builder,
        changeName: String,
        keyType: TypeName,
        valueType: TypeName,
        keyExpr: String,
        itemExpr: String,
        emit: Emit,
    ) {
        val rec = "rec$changeName"
        val changeList = MUTABLE_CHANGE_LIST.parameterizedBy(emit.changeType).copy(nullable = true)
        remember(emit, rec) {
            FunSpec.builder(rec)
                .addModifiers(KModifier.PRIVATE)
                .addParameter("changes", changeList)
                .addParameter("id", keyType)
                .addParameter("item", valueType)
                .returns(changeList.copy(nullable = false))
                .addStatement(
                    "return %T.add(changes, %T.%N(id, item))",
                    DIFFER_SUPPORT, emit.changeType, changeName,
                )
                .build()
        }
        out.addStatement("changes = $rec(changes, $keyExpr, $itemExpr)")
    }

    private fun remember(emit: Emit, name: String, build: () -> FunSpec) {
        if (emit.recorders.any { it.name == name }) return
        emit.recorders += build()
    }

    private fun KSType.sequenceKind(): CollectionKind? {
        val t = makeNotNullable()
        if (resolver.assigns(t, "kotlin.collections.Map", "java.util.Map")) return CollectionKind.MAP
        if (resolver.assigns(t, "kotlin.collections.List", "java.util.List")) return CollectionKind.LIST
        if (resolver.assigns(t, "kotlin.collections.Set", "java.util.Set")) return CollectionKind.SET
        return null
    }
}

private val MUTABLE_CHANGE_LIST = ClassName("kotlin.collections", "MutableList")
private val HASH_MAP = ClassName("java.util", "HashMap")
private val PAIR = ClassName("kotlin", "Pair")

private enum class CollectionKind { LIST, SET, MAP }

private fun Resolver.assigns(type: KSType, vararg names: String): Boolean =
    names.any { qn ->
        getClassDeclarationByName(qn)?.asStarProjectedType()?.isAssignableFrom(type) == true
    }

private fun KSType.isScalarValue(): Boolean {
    val t = makeNotNullable()
    val decl = t.declaration
    if (decl is KSClassDeclaration && decl.classKind == ClassKind.ENUM_CLASS) return true
    return decl.qualifiedName?.asString() in SCALAR_TYPES
}

private val SCALAR_TYPES = setOf(
    "kotlin.String", "kotlin.CharSequence",
    "kotlin.Int", "kotlin.Long", "kotlin.Short", "kotlin.Byte",
    "kotlin.Double", "kotlin.Float", "kotlin.Boolean", "kotlin.Char",
    "kotlin.UInt", "kotlin.ULong", "kotlin.UShort", "kotlin.UByte",
    "java.lang.String", "java.lang.Integer", "java.lang.Long",
    "java.lang.Short", "java.lang.Byte", "java.lang.Double",
    "java.lang.Float", "java.lang.Boolean", "java.lang.Character",
)

private fun KeyedList.snapshot(expr: String): CodeBlock = when (kind) {
    CollectionKind.LIST ->
        if (nullable) CodeBlock.of("$expr ?: emptyList()") else CodeBlock.of("%L", expr)
    CollectionKind.SET ->
        if (nullable) CodeBlock.of("$expr ?: emptySet()") else CodeBlock.of("%L", expr)
    CollectionKind.MAP -> error("list snapshot of map")
}

private fun KeyedMap.snapshot(expr: String): CodeBlock =
    if (nullable) CodeBlock.of("$expr ?: emptyMap()") else CodeBlock.of("%L", expr)

private interface HasBit {
    val index: Int
    val hasName: String
}

private data class PresenceBit(
    override val index: Int,
    override val hasName: String,
) : HasBit

private interface KeyedBag {
    val name: String
    val keyType: TypeName
    val deltaName: String
    val children: List<Node>
}

private sealed class Node {
    abstract fun slots(): List<HasBit>
    abstract fun bags(): List<KeyedBag>
    abstract fun walk(): Sequence<Node>

    data class Scalar(
        override val index: Int,
        val name: String,
        val path: String,
        val type: TypeName,
        val captureValues: Boolean,
        override val hasName: String,
        val changeName: String,
        val bag: KeyedBag?,
        val deltaProp: String?,
    ) : Node(), HasBit {
        override fun slots() = listOf(this)
        override fun bags() = emptyList<KeyedBag>()
        override fun walk() = sequenceOf(this)
    }

    data class Nested(
        val name: String,
        val children: List<Node>,
        val type: TypeName,
        val nullable: Boolean,
        val presenceIndex: Int?,
        val hasName: String?,
        val changeName: String?,
        val bag: KeyedBag?,
        val deltaProp: String?,
    ) : Node() {
        override fun slots(): List<HasBit> {
            val bits = ArrayList<HasBit>()
            val presence = presenceIndex
            val presenceHas = hasName
            if (presence != null && presenceHas != null) {
                bits += PresenceBit(presence, presenceHas)
            }
            bits += children.flatMap { it.slots() }
            return bits
        }

        override fun bags() = children.flatMap { it.bags() }
        override fun walk() = sequenceOf(this) + children.asSequence().flatMap { it.walk() }
    }

    data class KeyedList(
        override val name: String,
        val matchBy: String,
        override val keyType: TypeName,
        val elementType: TypeName,
        val addedIndex: Int,
        val removedIndex: Int,
        val addedHas: String,
        val removedHas: String,
        val addedChange: String,
        val removedChange: String,
        override val deltaName: String,
        val nullable: Boolean,
        val kind: CollectionKind,
        override val children: List<Node>,
    ) : Node(), KeyedBag {
        override fun slots(): List<HasBit> {
            val bits = ArrayList<HasBit>()
            bits += PresenceBit(addedIndex, addedHas)
            bits += PresenceBit(removedIndex, removedHas)
            bits += children.flatMap { it.slots() }
            return bits
        }

        override fun bags(): List<KeyedBag> = listOf(this) + children.flatMap { it.bags() }

        override fun walk() = sequenceOf(this) + children.asSequence().flatMap { it.walk() }
    }

    data class KeyedMap(
        override val name: String,
        override val keyType: TypeName,
        val valueType: TypeName,
        val addedIndex: Int,
        val removedIndex: Int,
        val addedHas: String,
        val removedHas: String,
        val addedChange: String,
        val removedChange: String,
        override val deltaName: String,
        val nullable: Boolean,
        override val children: List<Node>,
    ) : Node(), KeyedBag {
        override fun slots(): List<HasBit> {
            val bits = ArrayList<HasBit>()
            bits += PresenceBit(addedIndex, addedHas)
            bits += PresenceBit(removedIndex, removedHas)
            bits += children.flatMap { it.slots() }
            return bits
        }

        override fun bags(): List<KeyedBag> = listOf(this) + children.flatMap { it.bags() }

        override fun walk() = sequenceOf(this) + children.asSequence().flatMap { it.walk() }
    }
}

private data class DeltaField(val prop: String, val type: TypeName)

private fun KeyedBag.deltaFields(): List<DeltaField> {
    fun collect(nodes: List<Node>): List<DeltaField> = nodes.flatMap { node ->
        when (node) {
            is Scalar -> listOf(DeltaField(node.deltaProp!!, node.type))
            is Nested -> {
                val self = node.deltaProp?.let { listOf(DeltaField(it, node.type)) } ?: emptyList()
                self + collect(node.children)
            }
            is KeyedList, is KeyedMap -> emptyList()
        }
    }
    return collect(children)
}

private fun hasName(path: String) = "has" + typeName(path)

private fun typeName(path: String): String {
    val added = path.endsWith("[+]")
    val removed = path.endsWith("[-]")
    val core = path
        .removeSuffix("[+]")
        .removeSuffix("[-]")
        .replace("[]", "")
        .split('.')
        .filter { it.isNotEmpty() }
        .joinToString("") { part -> part.replaceFirstChar { it.uppercaseChar() } }
    return when {
        added -> "${core}Added"
        removed -> "${core}Removed"
        else -> core
    }
}

private fun deltaField(fullPath: String, listName: String): String {
    val prefix = "$listName[]."
    val rest = if (fullPath.startsWith(prefix)) fullPath.removePrefix(prefix) else fullPath.substringAfterLast("[]").trimStart('.')
    return rest.split('.')
        .filter { it.isNotEmpty() }
        .mapIndexed { i, part -> if (i == 0) part else part.replaceFirstChar { it.uppercaseChar() } }
        .joinToString("")
}

private fun KSAnnotated.annotationOf(qualifiedName: String): KSAnnotation? =
    annotations.firstOrNull { it.annotationType.resolve().declaration.qualifiedName?.asString() == qualifiedName }

private fun KSAnnotation.argument(name: String): Any? =
    arguments.firstOrNull { it.name?.asString() == name }?.value

private fun KSPropertyDeclaration.classDeclaration(): KSClassDeclaration? =
    type.resolve().declaration as? KSClassDeclaration

private fun KSPropertyDeclaration.elementDeclaration(): KSClassDeclaration? =
    type.resolve().arguments.firstOrNull()?.type?.resolve()?.declaration as? KSClassDeclaration
