package hana.differ.processor

import com.google.devtools.ksp.getDeclaredProperties
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MAP
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asClassName
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo
import hana.differ.processor.Node.KeyedList
import hana.differ.processor.Node.Nested
import hana.differ.processor.Node.Scalar

class DifferProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        DifferProcessor(environment.codeGenerator, environment.logger)
}

private const val ANNOTATION_PACKAGE = "hana.differ"
private const val DIFFER = "$ANNOTATION_PACKAGE.Differ"
private const val TRACKED = "$ANNOTATION_PACKAGE.Tracked"
private const val TRACKED_NESTED = "$ANNOTATION_PACKAGE.TrackedNested"
private const val TRACKED_LIST = "$ANNOTATION_PACKAGE.TrackedList"

private val DIFFER_SUPPORT = ClassName(ANNOTATION_PACKAGE, "DifferSupport")
private val VALUE_CHANGE = ClassName(ANNOTATION_PACKAGE, "ValueChange")
private val DUPLICATE_CHILD_ID = ClassName(ANNOTATION_PACKAGE, "DuplicateChildIdException")

class DifferProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        resolver.getSymbolsWithAnnotation(DIFFER)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { generate(it) }
        return emptyList()
    }

    private fun generate(cls: KSClassDeclaration) {
        val annotation = cls.annotationOf(DIFFER) ?: return
        val model = cls.toClassName()
        val objectName = (annotation.argument("name") as? String)
            ?.takeIf { it.isNotBlank() }
            ?: "${cls.simpleName.asString()}Differ"
        val diffName = "${cls.simpleName.asString()}Diff"
        val changeName = "${cls.simpleName.asString()}Change"

        val counter = intArrayOf(0)
        val roots = analyze(cls, path = "", list = null, counter = counter)
        val slotCount = counter[0]
        if (slotCount == 0) {
            logger.warn("@Differ class has no @Tracked properties; skipping", cls)
            return
        }
        if (slotCount > 64) {
            logger.error("@Differ class declares $slotCount tracked attributes; the Long mask holds 64", cls)
            return
        }

        val lists = roots.flatMap { it.lists() }
        val slots = roots.flatMap { it.slots() }
        val pkg = model.packageName
        val changeType = ClassName(pkg, changeName)
        val diffType = ClassName(pkg, diffName)

        val file = FileSpec.builder(pkg, objectName)
            .addFileComment("Generated by Differ. Do not edit.")
            .addType(changeInterface(changeType, roots))
            .apply { lists.forEach { addType(deltaClass(it)) } }
            .addType(rebuildDiffClass(diffType, slots, lists, changeType))
            .addType(differObject(objectName, model, diffType, changeType, roots, lists))
            .build()
        file.writeTo(codeGenerator, aggregating = false, originatingKSFiles = listOfNotNull(cls.containingFile))
    }

    private fun analyze(
        cls: KSClassDeclaration,
        path: String,
        list: KeyedList?,
        counter: IntArray,
    ): List<Node> {
        val out = ArrayList<Node>()
        for (prop in cls.getDeclaredProperties()) {
            val name = prop.simpleName.asString()
            when {
                prop.annotationOf(TRACKED) != null -> {
                    val capture = (prop.annotationOf(TRACKED)!!.argument("captureValues") as? Boolean) ?: true
                    val index = counter[0]++
                    val slotPath = path + name
                    out += Scalar(
                        index = index,
                        name = name,
                        path = slotPath,
                        type = prop.type.toTypeName(),
                        captureValues = capture,
                        hasName = hasName(slotPath),
                        changeName = typeName(slotPath),
                        list = list,
                        deltaProp = list?.let { deltaField(slotPath, it.name) },
                    )
                }
                prop.annotationOf(TRACKED_NESTED) != null -> {
                    val child = prop.classDeclaration() ?: run {
                        logger.error("@TrackedNested property is not a class type", prop)
                        return out
                    }
                    val slotPath = path + name
                    val nullable = prop.type.resolve().isMarkedNullable
                    val presenceIndex = if (nullable) counter[0]++ else null
                    out += Nested(
                        name = name,
                        children = analyze(child, "$path$name.", list, counter),
                        type = prop.type.toTypeName(),
                        nullable = nullable,
                        presenceIndex = presenceIndex,
                        hasName = if (nullable) hasName(slotPath) else null,
                        changeName = if (nullable) typeName(slotPath) else null,
                        list = list,
                        deltaProp = if (nullable) list?.let { deltaField(slotPath, it.name) } else null,
                    )
                }
                prop.annotationOf(TRACKED_LIST) != null -> {
                    val matchBy = (prop.annotationOf(TRACKED_LIST)!!.argument("matchBy") as? String) ?: "id"
                    val element = prop.elementDeclaration() ?: run {
                        logger.error("@TrackedList property is not a List<T> of a class type", prop)
                        return out
                    }
                    val keyProp = element.getDeclaredProperties().firstOrNull { it.simpleName.asString() == matchBy }
                    if (keyProp == null) {
                        logger.error("@TrackedList matchBy '$matchBy' not found on ${element.simpleName.asString()}", prop)
                        return out
                    }
                    val added = counter[0]++
                    val removed = counter[0]++
                    val addedPath = "$path$name[+]"
                    val removedPath = "$path$name[-]"
                    val spec = KeyedList(
                        name = name,
                        matchBy = matchBy,
                        keyType = keyProp.type.toTypeName(),
                        elementType = element.toClassName(),
                        addedIndex = added,
                        removedIndex = removed,
                        addedHas = hasName(addedPath),
                        removedHas = hasName(removedPath),
                        addedChange = typeName(addedPath),
                        removedChange = typeName(removedPath),
                        deltaName = typeName(name) + "Change",
                        nullable = prop.type.resolve().isMarkedNullable,
                        children = emptyList(),
                    )
                    val children = analyze(element, "$path$name[].", spec, counter)
                    out += spec.copy(children = children)
                }
            }
        }
        return out
    }

    private fun changeInterface(changeType: ClassName, roots: List<Node>): TypeSpec {
        val spec = TypeSpec.interfaceBuilder(changeType)
            .addModifiers(KModifier.SEALED)
        for (node in roots.asSequence().flatMap { it.walk() }) {
            when (node) {
                is Scalar -> spec.addType(scalarChange(changeType, node))
                is KeyedList -> {
                    spec.addType(boundChange(changeType, node.addedChange, node.keyType, node.elementType))
                    spec.addType(boundChange(changeType, node.removedChange, node.keyType, node.elementType))
                }
                is Nested -> if (node.presenceIndex != null) spec.addType(presenceChange(changeType, node))
            }
        }
        return spec.build()
    }

    private fun scalarChange(changeType: ClassName, node: Scalar): TypeSpec {
        val nested = changeType.nestedClass(node.changeName)
        if (!node.captureValues) {
            return TypeSpec.objectBuilder(node.changeName)
                .addModifiers(KModifier.DATA)
                .addSuperinterface(changeType)
                .build()
        }
        val ctor = FunSpec.constructorBuilder()
        val type = TypeSpec.classBuilder(node.changeName)
            .addModifiers(KModifier.DATA)
            .addSuperinterface(changeType)
        if (node.list != null) {
            ctor.addParameter("id", node.list.keyType)
            type.addProperty(PropertySpec.builder("id", node.list.keyType).initializer("id").build())
        }
        ctor.addParameter("old", node.type)
        ctor.addParameter("new", node.type)
        type.addProperty(PropertySpec.builder("old", node.type).initializer("old").build())
        type.addProperty(PropertySpec.builder("new", node.type).initializer("new").build())
        type.primaryConstructor(ctor.build())
        return type.build()
    }

    private fun presenceChange(changeType: ClassName, node: Nested): TypeSpec {
        val ctor = FunSpec.constructorBuilder()
        val type = TypeSpec.classBuilder(node.changeName!!)
            .addModifiers(KModifier.DATA)
            .addSuperinterface(changeType)
        if (node.list != null) {
            ctor.addParameter("id", node.list.keyType)
            type.addProperty(PropertySpec.builder("id", node.list.keyType).initializer("id").build())
        }
        ctor.addParameter("old", node.type)
        ctor.addParameter("new", node.type)
        type.addProperty(PropertySpec.builder("old", node.type).initializer("old").build())
        type.addProperty(PropertySpec.builder("new", node.type).initializer("new").build())
        type.primaryConstructor(ctor.build())
        return type.build()
    }

    private fun boundChange(changeType: ClassName, name: String, keyType: TypeName, elementType: TypeName): TypeSpec {
        return TypeSpec.classBuilder(name)
            .addModifiers(KModifier.DATA)
            .addSuperinterface(changeType)
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("id", keyType)
                    .addParameter("item", elementType)
                    .build(),
            )
            .addProperty(PropertySpec.builder("id", keyType).initializer("id").build())
            .addProperty(PropertySpec.builder("item", elementType).initializer("item").build())
            .build()
    }

    private fun deltaClass(list: KeyedList): TypeSpec {
        val spec = TypeSpec.classBuilder(list.deltaName)
        for (field in list.deltaFields()) {
            val t = VALUE_CHANGE.parameterizedBy(field.type).copy(nullable = true)
            spec.addProperty(
                PropertySpec.builder(field.prop, t)
                    .mutable()
                    .initializer("null")
                    .build(),
            )
        }
        return spec.build()
    }

    private fun rebuildDiffClass(
        diffType: ClassName,
        slots: List<HasBit>,
        lists: List<KeyedList>,
        changeType: ClassName,
    ): TypeSpec {
        val ctor = FunSpec.constructorBuilder().addModifiers(KModifier.INTERNAL)
        ctor.addParameter("mask", Long::class)
        ctor.addParameter("changes", List::class.asClassName().parameterizedBy(changeType))
        for (list in lists) {
            ctor.addParameter(list.name, MAP.parameterizedBy(list.keyType, ClassName(diffType.packageName, list.deltaName)))
        }
        val type = TypeSpec.classBuilder(diffType).primaryConstructor(ctor.build())
        type.addProperty(PropertySpec.builder("mask", Long::class, KModifier.PRIVATE).initializer("mask").build())
        type.addProperty(
            PropertySpec.builder("changes", List::class.asClassName().parameterizedBy(changeType))
                .initializer("changes")
                .build(),
        )
        type.addProperty(
            PropertySpec.builder("hasChanged", Boolean::class)
                .getter(FunSpec.getterBuilder().addStatement("return mask != 0L").build())
                .build(),
        )
        for (slot in slots) {
            type.addProperty(
                PropertySpec.builder(slot.hasName, Boolean::class)
                    .getter(
                        FunSpec.getterBuilder()
                            .addStatement("return mask and %L != 0L", 1L shl slot.index)
                            .build(),
                    )
                    .build(),
            )
        }
        for (list in lists) {
            val mapType = MAP.parameterizedBy(list.keyType, ClassName(diffType.packageName, list.deltaName))
            type.addProperty(PropertySpec.builder(list.name, mapType).initializer(list.name).build())
        }
        return type.build()
    }

    private fun differObject(
        objectName: String,
        model: ClassName,
        diffType: ClassName,
        changeType: ClassName,
        roots: List<Node>,
        lists: List<KeyedList>,
    ): TypeSpec {
        val body = CodeBlock.builder()
        body.addStatement("var mask = 0L")
        body.addStatement("var changes: %T = null", MUTABLE_CHANGE_LIST.parameterizedBy(changeType).copy(nullable = true))
        for (list in lists) {
            val map = HASH_MAP.parameterizedBy(list.keyType, ClassName(model.packageName, list.deltaName))
            body.addStatement("var ${list.name}: %T = null", map.copy(nullable = true))
        }
        emitNodes(body, roots, oldExpr = "old", newExpr = "new", depth = 0, keyLocal = null, changeType = changeType)
        val args = ArrayList<Any>()
        val names = StringBuilder("return %T(mask, changes ?: emptyList()")
        args += diffType
        for (list in lists) {
            names.append(", ${list.name} ?: emptyMap()")
        }
        names.append(")")
        body.addStatement(names.toString(), *args.toTypedArray())

        return TypeSpec.objectBuilder(objectName)
            .addFunction(
                FunSpec.builder("diff")
                    .addParameter("old", model)
                    .addParameter("new", model)
                    .returns(diffType)
                    .addCode(body.build())
                    .build(),
            )
            .build()
    }

    private fun emitNodes(
        out: CodeBlock.Builder,
        nodes: List<Node>,
        oldExpr: String,
        newExpr: String,
        depth: Int,
        keyLocal: String?,
        changeType: ClassName,
    ) {
        for (node in nodes) {
            when (node) {
                is Scalar -> emitScalar(out, node, oldExpr, newExpr, keyLocal, changeType)
                is Nested -> emitNested(out, node, oldExpr, newExpr, depth, keyLocal, changeType)
                is KeyedList -> emitList(out, node, oldExpr, newExpr, depth, changeType)
            }
        }
    }

    private fun emitNested(
        out: CodeBlock.Builder,
        node: Nested,
        oldExpr: String,
        newExpr: String,
        depth: Int,
        keyLocal: String?,
        changeType: ClassName,
    ) {
        val oldAccess = "$oldExpr.${node.name}"
        val newAccess = "$newExpr.${node.name}"
        if (!node.nullable) {
            emitNodes(out, node.children, oldAccess, newAccess, depth, keyLocal, changeType)
            return
        }
        val presence = node.presenceIndex ?: return
        out.beginControlFlow("if ($oldAccess == null && $newAccess == null)")
        out.nextControlFlow("else if ($oldAccess == null || $newAccess == null)")
        out.addStatement("mask = mask or %L", 1L shl presence)
        if (node.list != null && keyLocal != null) {
            out.addStatement(
                "changes = %T.add(changes, %T.%N(%L, %L, %L))",
                DIFFER_SUPPORT, changeType, node.changeName!!, keyLocal, oldAccess, newAccess,
            )
            if (node.deltaProp != null) {
                val deltaType = ClassName(changeType.packageName, node.list.deltaName)
                out.addStatement(
                    "val held = %T.child(${node.list.name}, %L) { %T() }",
                    DIFFER_SUPPORT, keyLocal, deltaType,
                )
                out.addStatement("${node.list.name} = held.map")
                out.addStatement("held.value.${node.deltaProp} = %T(%L, %L)", VALUE_CHANGE, oldAccess, newAccess)
            }
        } else {
            out.addStatement(
                "changes = %T.add(changes, %T.%N(%L, %L))",
                DIFFER_SUPPORT, changeType, node.changeName!!, oldAccess, newAccess,
            )
        }
        out.nextControlFlow("else")
        emitNodes(out, node.children, oldAccess, newAccess, depth, keyLocal, changeType)
        out.endControlFlow()
    }

    private fun emitScalar(
        out: CodeBlock.Builder,
        node: Scalar,
        oldExpr: String,
        newExpr: String,
        keyLocal: String?,
        changeType: ClassName,
    ) {
        val oldAccess = "$oldExpr.${node.name}"
        val newAccess = "$newExpr.${node.name}"
        val deltaType = node.list?.let { ClassName(changeType.packageName, it.deltaName) }
        out.beginControlFlow("if ($oldAccess != $newAccess)")
        out.addStatement("mask = mask or %L", 1L shl node.index)
        if (node.captureValues) {
            if (node.list != null && keyLocal != null && deltaType != null) {
                out.addStatement(
                    "changes = %T.add(changes, %T.%N(%L, %L, %L))",
                    DIFFER_SUPPORT, changeType, node.changeName, keyLocal, oldAccess, newAccess,
                )
                out.addStatement(
                    "val held = %T.child(${node.list.name}, %L) { %T() }",
                    DIFFER_SUPPORT, keyLocal, deltaType,
                )
                out.addStatement("${node.list.name} = held.map")
                out.addStatement("held.value.${node.deltaProp} = %T(%L, %L)", VALUE_CHANGE, oldAccess, newAccess)
            } else {
                out.addStatement(
                    "changes = %T.add(changes, %T.%N(%L, %L))",
                    DIFFER_SUPPORT, changeType, node.changeName, oldAccess, newAccess,
                )
            }
        } else {
            out.addStatement("changes = %T.add(changes, %T.%N)", DIFFER_SUPPORT, changeType, node.changeName)
        }
        out.endControlFlow()
    }

    private fun emitList(
        out: CodeBlock.Builder,
        list: KeyedList,
        oldExpr: String,
        newExpr: String,
        depth: Int,
        changeType: ClassName,
    ) {
        val d = depth
        val oldItems = "oldItems$d"
        val newItems = "newItems$d"
        val index = "index$d"
        val visited = "visited$d"
        val i = "i$d"
        val item = "item$d"
        val key = "k$d"
        val found = "found$d"
        val prior = "prior$d"

        out.beginControlFlow("run")
        if (list.nullable) {
            out.addStatement("val $oldItems = $oldExpr.${list.name} ?: emptyList()")
            out.addStatement("val $newItems = $newExpr.${list.name} ?: emptyList()")
        } else {
            out.addStatement("val $oldItems = $oldExpr.${list.name}")
            out.addStatement("val $newItems = $newExpr.${list.name}")
        }
        out.addStatement("val $index = %T<%T, Int>($oldItems.size * 2)", HASH_MAP, list.keyType)
        out.beginControlFlow("for ($i in $oldItems.indices)")
        out.addStatement("val stored = $oldItems[$i].${list.matchBy}")
        val idArg = if (list.keyType.copy(nullable = false) == STRING) "stored" else "stored.toString()"
        out.addStatement("if ($index.put(stored, $i) != null) throw %T(%L)", DUPLICATE_CHILD_ID, idArg)
        out.endControlFlow()
        out.addStatement("val $visited = BooleanArray($oldItems.size)")
        out.beginControlFlow("for ($item in $newItems)")
        out.addStatement("val $key = $item.${list.matchBy}")
        out.addStatement("val $found = $index[$key]")
        out.beginControlFlow("if ($found == null)")
        out.addStatement("mask = mask or %L", 1L shl list.addedIndex)
        out.addStatement(
            "changes = %T.add(changes, %T.%N($key, $item))",
            DIFFER_SUPPORT, changeType, list.addedChange,
        )
        out.addStatement("continue")
        out.endControlFlow()
        out.addStatement("$visited[$found] = true")
        out.addStatement("val $prior = $oldItems[$found]")
        emitNodes(out, list.children, prior, item, depth, key, changeType)
        out.endControlFlow()
        out.beginControlFlow("for ($i in $oldItems.indices)")
        out.addStatement("if ($visited[$i]) continue")
        out.addStatement("mask = mask or %L", 1L shl list.removedIndex)
        out.addStatement(
            "changes = %T.add(changes, %T.%N($oldItems[$i].${list.matchBy}, $oldItems[$i]))",
            DIFFER_SUPPORT, changeType, list.removedChange,
        )
        out.endControlFlow()
        out.endControlFlow()
    }
}

private val MUTABLE_CHANGE_LIST = ClassName("kotlin.collections", "MutableList")
private val HASH_MAP = ClassName("java.util", "HashMap")

private interface HasBit {
    val index: Int
    val hasName: String
}

private data class PresenceBit(
    override val index: Int,
    override val hasName: String,
) : HasBit

private sealed class Node {
    abstract fun slots(): List<HasBit>
    abstract fun lists(): List<KeyedList>
    abstract fun walk(): Sequence<Node>

    data class Scalar(
        override val index: Int,
        val name: String,
        val path: String,
        val type: TypeName,
        val captureValues: Boolean,
        override val hasName: String,
        val changeName: String,
        val list: KeyedList?,
        val deltaProp: String?,
    ) : Node(), HasBit {
        override fun slots() = listOf(this)
        override fun lists() = emptyList<KeyedList>()
        override fun walk() = sequenceOf(this)
    }

    data class Nested(
        val name: String,
        val children: List<Node>,
        val type: TypeName,
        val nullable: Boolean,
        val presenceIndex: Int?,
        val hasName: String?,
        val changeName: String?,
        val list: KeyedList?,
        val deltaProp: String?,
    ) : Node() {
        override fun slots(): List<HasBit> {
            val bits = ArrayList<HasBit>()
            val presence = presenceIndex
            val presenceHas = hasName
            if (presence != null && presenceHas != null) {
                bits += PresenceBit(presence, presenceHas)
            }
            bits += children.flatMap { it.slots() }
            return bits
        }

        override fun lists() = children.flatMap { it.lists() }
        override fun walk() = sequenceOf(this) + children.asSequence().flatMap { it.walk() }
    }

    data class KeyedList(
        val name: String,
        val matchBy: String,
        val keyType: TypeName,
        val elementType: TypeName,
        val addedIndex: Int,
        val removedIndex: Int,
        val addedHas: String,
        val removedHas: String,
        val addedChange: String,
        val removedChange: String,
        val deltaName: String,
        val nullable: Boolean,
        val children: List<Node>,
    ) : Node() {
        override fun slots(): List<HasBit> {
            val bits = ArrayList<HasBit>()
            bits += object : HasBit {
                override val index = addedIndex
                override val hasName = addedHas
            }
            bits += object : HasBit {
                override val index = removedIndex
                override val hasName = removedHas
            }
            bits += children.flatMap { it.slots() }
            return bits
        }

        override fun lists(): List<KeyedList> = listOf(this) + children.flatMap { it.lists() }

        override fun walk() = sequenceOf(this) + children.asSequence().flatMap { it.walk() }
    }
}

private data class DeltaField(val prop: String, val type: TypeName)

private fun KeyedList.deltaFields(): List<DeltaField> {
    fun collect(nodes: List<Node>): List<DeltaField> = nodes.flatMap { node ->
        when (node) {
            is Scalar -> listOf(DeltaField(node.deltaProp!!, node.type))
            is Nested -> {
                val self = node.deltaProp?.let { listOf(DeltaField(it, node.type)) } ?: emptyList()
                self + collect(node.children)
            }
            is KeyedList -> emptyList()
        }
    }
    return collect(children)
}

private fun hasName(path: String) = "has" + typeName(path)

private fun typeName(path: String): String {
    val added = path.endsWith("[+]")
    val removed = path.endsWith("[-]")
    val core = path
        .removeSuffix("[+]")
        .removeSuffix("[-]")
        .replace("[]", "")
        .split('.')
        .filter { it.isNotEmpty() }
        .joinToString("") { part -> part.replaceFirstChar { it.uppercaseChar() } }
    return when {
        added -> "${core}Added"
        removed -> "${core}Removed"
        else -> core
    }
}

private fun deltaField(fullPath: String, listName: String): String {
    val prefix = "$listName[]."
    val rest = if (fullPath.startsWith(prefix)) fullPath.removePrefix(prefix) else fullPath.substringAfterLast("[]").trimStart('.')
    return rest.split('.')
        .filter { it.isNotEmpty() }
        .mapIndexed { i, part -> if (i == 0) part else part.replaceFirstChar { it.uppercaseChar() } }
        .joinToString("")
}

private fun KSAnnotated.annotationOf(qualifiedName: String): KSAnnotation? =
    annotations.firstOrNull { it.annotationType.resolve().declaration.qualifiedName?.asString() == qualifiedName }

private fun KSAnnotation.argument(name: String): Any? =
    arguments.firstOrNull { it.name?.asString() == name }?.value

private fun KSPropertyDeclaration.classDeclaration(): KSClassDeclaration? =
    type.resolve().declaration as? KSClassDeclaration

private fun KSPropertyDeclaration.elementDeclaration(): KSClassDeclaration? =
    type.resolve().arguments.firstOrNull()?.type?.resolve()?.declaration as? KSClassDeclaration
